# Generated by Django 6.1.1 on 2026-09-16 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaksegment',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studysegment',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
