# Generated by Django 6.1.1 on 2026-09-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysessions', '0002_alter_breaksegment_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='checked_in',
            field=models.BooleanField(default=False, help_text='True once the post-session log prompt has been resolved.'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='manual_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Study time the user confirmed and credited to the course.'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='target_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Planned focus time in minutes. Empty means free focus (no timer).', null=True),
        ),
    ]
