# Generated by Django 6.1.1 on 2026-09-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='planned_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, max_length=300, verbose_name='Course link'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.FloatField(default=0, verbose_name='Course hours'),
        ),
    ]
