# Generated by Django 6.1.1 on 2026-09-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_roadmap_roadmapcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapcourse',
            name='planned_hours',
            field=models.FloatField(default=0, verbose_name='Planned hours'),
        ),
    ]
