# Generated by Django 6.1.1 on 2026-09-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_roadmapcourse_planned_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapcourse',
            name='link',
            field=models.URLField(blank=True, max_length=300, verbose_name='Course link'),
        ),
    ]
