# Generated by Django 5.2.8 on 2026-09-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_roadmapcourse_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roadmapcourse',
            name='unique_roadmap_course',
        ),
        migrations.AlterField(
            model_name='roadmapcourse',
            name='course_title_override',
            field=models.CharField(blank=True, max_length=120, verbose_name='Course title'),
        ),
    ]
