# Generated by Django 5.2.8 on 2026-10-05 14:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_roadmapcourse_unique_roadmap_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='forked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='courses.course'),
        ),
        migrations.AddField(
            model_name='roadmapcourse',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0, help_text='Set by hand for roadmap-only courses. Linked courses report their own progress.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
